efc_product:
    resource: "@EfcProductBundle/Resources/config/routing.yml"
    prefix:   /product

efc_catalogue:
    resource: "@EfcCatalogueBundle/Resources/config/routing.yml"
    prefix:   /catalogue

efc_ecommerce:
    resource: "@EfcEcommerceBundle/Resources/config/routing.yml"
    prefix:   /