version: '2'
services:
  phpfpm:
    build:
      context: ../..
      dockerfile: etc/docker/Dockerfile_php
    expose:
      - '9000'
    depends_on:
      - mysql
    volumes:
      - ../../app/:/var/www/symfony/app:cached
      - ../../bin/:/var/www/symfony/bin:cached
      - ../../src/:/var/www/symfony/src:cached
      - ../../tests/:/var/www/symfony/tests:cached
      - ../../web/:/var/www/symfony/web:cached
      - symfony_var:/var/www/symfony/var:cached
      - symfony_vendor:/var/www/symfony/vendor:cached
  nginx:
    build:
      context: ../..
      dockerfile: etc/docker/Dockerfile_nginx
    restart: always
    ports:
      - '8042:80'
    depends_on:
      - phpfpm
      - mysql
    volumes:
      - ../../app/:/var/www/symfony/app:cached
      - ../../bin/:/var/www/symfony/bin:cached
      - ../../src/:/var/www/symfony/src:cached
      - ../../tests/:/var/www/symfony/tests:cached
      - ../../web/:/var/www/symfony/web:cached
      - symfony_var:/var/www/symfony/var:cached
      - symfony_vendor:/var/www/symfony/vendor:cached
  mysql:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=changeIt
      - MYSQL_ALLOW_EMPTY_PASSWORD=false
    ports:
      - "3307:3306"
    volumes:
      - symfony_mysql:/var/lib/mysql
      - ../mysql:/docker-entrypoint-initdb.d
volumes:
  symfony_mysql:
  symfony_vendor:
  symfony_var:
networks:
  default:
    external:
      name: symfony_dev