version: '2'
services:
  phpfpm:
    build:
      context: ../..
      dockerfile: etc/docker/Dockerfile_php
    expose:
      - '9000'
    depends_on:
      - mysql
    volumes:
      - ../../src/:/var/www/symfony:cached
  nginx:
    build:
      context: ../..
      dockerfile: etc/docker/Dockerfile_nginx
    restart: always
    ports:
      - '8042:80'
    depends_on:
      - phpfpm
      - mysql
    volumes:
      - ../../src/:/var/www/symfony:cached
  mysql:
    image: mysql/mysql-server:latest
    environment:
      - MYSQL_DATABASE=symfony
      - MYSQL_ROOT_PASSWORD=changeIt
    ports:
      - "3307:3306"
    volumes:
      - symfony_mysql:/var/lib/mysql
volumes:
  symfony_mysql: