version: '2'
services:
  # *******************************************
  symfony_app:
    build:
      context: ../..
      dockerfile: etc/docker/Dockerfile
    container_name: symfony_app
    ports:
      - "8090:80"
      - "8043:443"
    volumes:
      - ../../app:/var/www/app/
      - ../../bin:/var/www/bin/
      - ../../html:/var/www/html/
      - ../../src:/var/www/src/
      - ../../tests:/var/www/tests/
      - ../../var:/var/www/var/
      - ../../vendor:/var/www/vendor/
      - ../../web:/var/www/web/
  # *******************************************
  symfony_mysql_db:
    image: mysql:5.6
    ports:
      - "30390:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=changeit
      - MYSQL_ALLOW_EMPTY_PASSWORD=false
    container_name: symfony_mysql_db
    volumes:
      - ../mysql:/docker-entrypoint-initdb.d
      - symfonymysqldb:/var/lib/mysql
# *******************************************
volumes:
  symfonymysqldb:
# *******************************************
networks:
  default:
    external:
      name: symfony_dev
