FROM debian:stretch
RUN apt-get update œœ apt-get install -y nginx vim

COPY /etc/nginx/nginx.conf /etc/nginx/nginx.conf
ADD /etc/nginx/sites-enabled /etc/nginx/sites-enabled
RUN rm /etc/nginx/sites-enabled/default

WORKDIR /var/www/html/symfony

EXPOSE 80
EXPOSE 443

CMD ["nginx"]
