version: '2'
services:
  php:
    build:
      context: ../..
      dockerfile: etc/docker/Dockerfile_php
    expose:
      - '9000'
    depends_on:
      - db
    volumes:
      - ./src/:/var/www/html/symfony:cached
  web:
    build:
      context: ../..
      dockerfile: etc/docker/Dockerfile_nginx
    restart: always
    ports:
      - '8042:80'
    depends_on:
      - php
      - db
    volumes:
      - ./src/:/var/www/html/symfony:cached
  db:
    image: mysql/mysql-server:latest
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_ROOT_HOST=${MYSQL_ROOT_HOST}
    ports:
      - "3307:3306"
    volumes:
      - symfony_mysql/:/var/lib/mysql